import { useState, useCallback } from 'react'
import { jsPDF } from 'jspdf'
import { exportPointsAsCSV, exportProjectAsJSON } from '../utils/storage'
import { calculateArea, calculatePerimeter, formatArea, formatDistance } from '../utils/calculations'
import { formatCoordinate } from '../utils/coordinates'
import ExportDialog from './ExportDialog'

export default function ExportPanel({ points, projectName, coordinateSystem, utmZone = 35 }) {
  const [showDialog, setShowDialog] = useState(false)

  const handleExportSimplePDF = useCallback(() => {
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()

    // Title
    doc.setFontSize(18)
    doc.text(projectName || 'Survey Report', pageWidth / 2, 20, { align: 'center' })

    // Date
    doc.setFontSize(10)
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, 28, { align: 'center' })

    // Summary
    doc.setFontSize(14)
    doc.text('Summary', 20, 45)

    const area = calculateArea(points)
    const perimeter = calculatePerimeter(points)

    doc.setFontSize(11)
    doc.text(`Number of Points: ${points.length}`, 20, 55)
    doc.text(`Total Area: ${formatArea(area)} (${area.hectares.toFixed(3)} ha)`, 20, 63)
    doc.text(`Perimeter: ${formatDistance(perimeter)}`, 20, 71)
    doc.text(`Coordinate System: ${coordinateSystem === 'utm' ? `UTM Zone ${utmZone}S` : 'WGS84'}`, 20, 79)

    // Points table
    doc.setFontSize(14)
    doc.text('Survey Points', 20, 95)

    doc.setFontSize(9)
    let y = 105

    // Table header
    doc.setFont(undefined, 'bold')
    doc.text('Point', 20, y)
    doc.text('Coordinates', 45, y)
    doc.setFont(undefined, 'normal')

    y += 8
    points.forEach((point, index) => {
      if (y > 270) {
        doc.addPage()
        y = 20
      }
      doc.text(`${index + 1}`, 20, y)
      doc.text(formatCoordinate(point, coordinateSystem, utmZone), 45, y)
      y += 6
    })

    // Footer
    doc.setFontSize(8)
    doc.text('Generated by Zambia Survey Tool', pageWidth / 2, 290, { align: 'center' })

    doc.save(`${projectName || 'survey'}-report.pdf`)
  }, [points, projectName, coordinateSystem, utmZone])

  const handleExportCSV = useCallback(() => {
    exportPointsAsCSV(points, coordinateSystem)
  }, [points, coordinateSystem])

  const handleExportJSON = useCallback(() => {
    exportProjectAsJSON({
      name: projectName,
      points,
      coordinateSystem,
      utmZone,
      exportedAt: new Date().toISOString()
    })
  }, [points, projectName, coordinateSystem, utmZone])

  return (
    <div className="panel export-panel">
      <h3>Export</h3>

      <div className="export-buttons">
        <button
          onClick={() => setShowDialog(true)}
          disabled={points.length < 3}
          style={{
            background: points.length >= 3 ? '#D97757' : '#ccc',
            color: 'white',
            border: 'none',
            fontWeight: '500'
          }}
        >
          Ministry of Lands PDF
        </button>
        <button onClick={handleExportSimplePDF} disabled={points.length < 3}>
          Simple PDF Report
        </button>
        <button onClick={handleExportCSV} disabled={points.length === 0}>
          Export Points (CSV)
        </button>
        <button onClick={handleExportJSON}>
          Export Project (JSON)
        </button>
      </div>

      {points.length < 3 && (
        <p style={{ color: '#666', fontSize: '0.8rem', marginTop: '0.5rem' }}>
          Add at least 3 points to export PDF
        </p>
      )}

      {showDialog && (
        <ExportDialog
          points={points}
          utmZone={utmZone}
          onClose={() => setShowDialog(false)}
        />
      )}
    </div>
  )
}
